### ISSUE TITLE
Default browser alert when clicking on "magic spell" button without any content written on the screen.

### ISSUE THREAD

**Issue by Nanak360** [VishwaGauravIn/pro-writer#16]
## The issue
Clicking on magic spell opens default browser alert. Alers do not close on clicking anywhere on the screen but only on the OK button.
![Screenshot 2023-04-25 at 9 38 19 PM](https://user-images.githubusercontent.com/36790357/234338762-53e39852-abd0-4642-95d1-afc35b83564e.png)

## Solutions
- (Solution 1) We can add a new popup, a snackbar or an alert via code (not browser default one) to display the message. Any library can be utilized ot we can create a custom one. 
- (Solution 2) We can disable the magic spell button unless requirements are met. On hovering over the button user can see a text like "Please add more suitable content to apply magic spell"

Oh and I am willing to work on this issue.

**Comment by VishwaGauravIn** [comment]
but why not the default alert?

**Comment by Nanak360** [comment]
Having a custom one will give a better feel to the website.

**Comment by VishwaGauravIn** [comment]
Yes but we are purposely using it as of now
