### ISSUE TITLE
Template section is not visible on small devices

### ISSUE THREAD

**Issue by pushkarydv** [VishwaGauravIn/pro-writer#8]
**Describe the bug**
The Popup of Template section is not visible in mobile devices due to it's `fixed` position in code. When window becomes small it's position get's out of the window and hence invisible. No issue in medium devices or greater

**To Reproduce**
Try resizing the window after opening popup

**Expected behavior**
Should be on top of template button

**Screenshots**
![image](https://user-images.githubusercontent.com/96358784/155524216-247effbc-e01c-4617-93c8-05a130580b05.png)

**Comment by VishwaGauravIn** [comment]
Issue Resolved.
Thanks for your valuable feedback.
